### ISSUE TITLE
Login button

### ISSUE THREAD

**Issue by nattikim** [merpw/forum#84]
We've lost the Login button at some stage (right side of navbar).. 

<img width="1492" alt="Screenshot 2023-07-15 at 01 16 53" src="https://github.com/merpw/forum/assets/93912586/017aa7a3-4514-428a-9203-4a1e98edf773">
<img width="1482" alt="Screenshot 2023-07-15 at 01 17 12" src="https://github.com/merpw/forum/assets/93912586/5b8660f5-6928-4a41-8a8d-3d73d5f49777">

**Comment by maximihajlov** [comment]
Everything is fine in revision #82, so this bug was caused by the recent design improvements in #74. This bug is not severe in private mode, but in public mode it makes impossible to login:

![image](https://github.com/merpw/forum/assets/43277901/aa18dec6-7a5a-4de7-b50a-f689b5b7efa9)


There's also unnecessary scroll bar in login and signup pages:

![image](https://github.com/merpw/forum/assets/43277901/a6f7bb86-42d4-47ae-9acb-94c49ff60988)
